### ISSUE TITLE
cannot import name '_C' from 'vc_rcnn' 

### ISSUE THREAD

**Issue by amanchadha** [Wangt-CN/VC-R-CNN#5]
'_C' in 'vc_rcnn/' appears to be missing. Command line and error is below:

$ python3 tools/test_net.py --config-file "configs/e2e_mask_rcnn_R_50_FPN_1x.yaml" TEST.IMS_PER_BATCH images_per_gpu x $GPUS
Traceback (most recent call last):
  File "tools/test_net.py", line 13, in <module>
    from vc_rcnn.data import make_data_loader
  File "./vc_rcnn/data/__init__.py", line 2, in <module>
    from .build import make_data_loader
  File "./vc_rcnn/data/build.py", line 11, in <module>
    from . import datasets as D
  File "./vc_rcnn/data/datasets/__init__.py", line 3, in <module>
    from .coco import COCODataset
  File "./vc_rcnn/data/datasets/coco.py", line 8, in <module>
    from vc_rcnn.structures.segmentation_mask import SegmentationMask
  File "./vc_rcnn/structures/segmentation_mask.py", line 5, in <module>
    from vc_rcnn.layers.misc import interpolate
  File "./vc_rcnn/layers/__init__.py", line 10, in <module>
    from .nms import nms
  File "./vc_rcnn/layers/nms.py", line 3, in <module>
    from vc_rcnn import _C
ImportError: cannot import name '_C' from 'vc_rcnn' (./vc_rcnn/__init__.py)

**Comment by Wangt-CN** [comment]
Sorry for the delay reply. Can you provide more exact commond? It seemed that you didn't install properly follow the `install.md`. Moreover,  you should change the `images_per_gpu x $GPUS` into int value.
You can also refer to the `maskrcnn-benchmark` [issue](https://github.com/facebookresearch/maskrcnn-benchmark/issues/614).
